spring:

   h2.console:
      enabled: true
      path: '/console'

   datasource:
      url: 'jdbc:h2:file:C:/Users/Admin/Documents/NetBeansProjects/todo-app_partTwo/todo-app'

   jpa:
      hibernate:
         ddl-auto: validate

      open-in-view: false

   flyway:
      baseline-on-migrate:
         true

task:
   allow-multiple-tasks-from-template: false

management:
   endpoints:
      web:
         exposure:
            include: '*'